.\"             -*-Nroff-*-
.\"  This page Copyright (C) 1993 Matt Welsh, mdw@tc.cornell.edu.
.\"  Freely distributable under the terms of the GPL
.TH TLOAD "1" "June 2011" "procps-ng" "User Commands"
.SH NAME
tload \- graphic representation of system load average
.SH SYNOPSIS
.B tload
[\fIoptions\fR] [\fItty\fR]
.SH DESCRIPTION
.B tload
prints a graph of the current system load average to the specified
.I tty
(or the tty of the tload process if none is specified).
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-scale\fR \fInumber\fR
The scale option allows a vertical scale to be specified for the display (in
characters between graph ticks); thus, a smaller value represents a larger
scale, and vice versa.
.TP
\fB\-d\fR, \fB\-\-delay\fR \fIseconds\fR
The delay sets the delay between graph updates in
.IR seconds .
.TP
\fB\-h\fR, \fB\-\-help\fR
Display this help text.
.TP
\fB\-V\fR, \fB\-\-version\fR
Display version information and exit.
.PP
.SH FILES
.I /proc/loadavg
load average information
.SH "SEE ALSO"
.BR ps (1),
.BR top (1),
.BR uptime (1),
.BR w (1)
.SH BUGS
The
.BI "\-d" " delay"
option sets the time argument for an
.BR alarm (2);
if \-d 0 is specified, the alarm is set to 0, which will never send the
.B SIGALRM
and update the display.
.SH AUTHORS
Branko Lankester,
.UR david@\:ods.\:com
David Engel
.UE , and
.UR johnsonm@\:redhat.\:com
Michael K. Johnson
.UE .
.SH "REPORTING BUGS"
Please send bug reports to
.UR procps@freelists.org
.UE
